spring.application.name=stock-control-api

logging.level.root=INFO
logging.level.io.github.stock_control_api=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/stock_control_db
spring.datasource.username=root
spring.datasource.password=892240

spring.jpa.hibernate.ddl-auto=validate
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# EMAIL

spring.mail.host=server44.integrator.com.br
spring.mail.port=465

spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true